Repository kata-containers/osbuilder, pull requests merged in 2020-12, with the labels that each got.

#502 Add support for Gentoo
  rootfs-builder/gentoo/Dockerfile.in
  rootfs-builder/gentoo/config.sh
  rootfs-builder/gentoo/rootfs_lib.sh
  rootfs-builder/rootfs.sh
  rootfs-builder/template/rootfs_lib_template.sh
  scripts/lib.sh
Labels: needs-forward-port, no-backport-needed

#510 backport: rootfs: Skip installing cargo and rust for docker build
  rootfs-builder/rootfs.sh
  rootfs-builder/template/rootfs_lib_template.sh
  scripts/lib.sh
Labels: backport

#509 backport: rootfs: Skip installing cargo and rust for docker build
  rootfs-builder/rootfs.sh
  rootfs-builder/template/rootfs_lib_template.sh
  scripts/lib.sh
Labels: backport

#512 github: Add github actions
  .github/workflows/main.yml
  .travis.yml
Labels: no-backport-needed, no-forward-port-needed
